### ISSUE TITLE
Update for Minecraft v1.15.2 ?

### ISSUE THREAD

**Issue by EHCanadian** [martinambrus/WGChestRefillFlag#1]
`[Server thread/ERROR]: Could not load 'plugins\wgchestrefil.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WGCustomFlags
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:236) [spigot.jar:git-Spigot-c574e08-37f32da]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:353) [spigot.jar:git-Spigot-c574e08-37f32da]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:210) [spigot.jar:git-Spigot-c574e08-37f32da]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot.jar:git-Spigot-c574e08-37f32da]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]`

**Comment by martinambrus** [comment]
This plugin is dependeng on [WorldGuard Custom Flags](https://dev.bukkit.org/projects/worldguard-custom-flags) which hasn't been updated for ages now. WGChestRefillFlag will work out of the box if/when WorldGuard Custom Flags is updated.
